### teste delogin
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{
    "UserName": "admin",
    "Password": "admin"
}

### teste de logout
POST http://localhost:40000/Logout HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzYzODc5NTgwLCJleHAiOjE3NjY0NzE1ODB9.UNTzoqGOLtb_NGpiwz903jhu0VMI9PmuFa1acRb34n4

{    
  
}

### 3. TESTE ROTA PROTEGIDA: GET ALL Medico
GET http://localhost:40000/getAllTutores HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzYzODc5NTgwLCJleHAiOjE3NjY0NzE1ODB9.UNTzoqGOLtb_NGpiwz903jhu0VMI9PmuFa1acRb34n4