### 1. AUTENTICAÇÃO (LOGIN)
# @name loginAutenticado
POST http://localhost:4000/Login HTTP/1.1
Content-Type: application/json

{
    "UserName": "admin", 
    "Password": "admin"
}

### Seta o token
@accessToken = {{loginAutenticado.response.body.token}}
//medico@IDCriado = {{insertNovoMedico.response.body.id}} 
---

### 2. INSERÇÃO (C) - InsertMedico
# @name insertNovoMedico
POST http://localhost:4000/insertMedico HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nomemedico": "Fernanda Lima",
    "especialidade":"Cardiologista"
}

### CAPTURA O ID DINÂMICO APÓS A INSERÇÃO DA REQUISIÇÃO ABAIXO (NOVA POSIÇÃO CORRETA)
@medicoIDCriado = {{insertNovoMedico.response.body.medicoid}} 

---

### 3. BUSCAR TODOS (R) - GetAllMedico
GET http://localhost:4000/getAllMedico HTTP/1.1
Authorization: Bearer {{accessToken}}

---

### 4. BUSCAR POR ID (R) - GetMedicoByID
POST http://localhost:4000/getMedicoByID HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "medicoid":2
}

### 5. ATUALIZAÇÃO (U) - UpdateMedico
POST http://localhost:4000/updateMedico HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "medicoid": 1,
    "nomemedico": "Fernanda Lima Montenegro",
    "especialidade":"Cardiologista"
}

### 6. SOFT DELETE (D) - DeleteMedico
POST http://localhost:4000/deleteMedico HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "medicoid": 1
}

### 7. VERIFICAÇÃO DE SOFT DELETE
POST http://localhost:4000/getMedicoByID HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "medicoid": 1
}